<a href="https://colab.research.google.com/github/DanielChamaco1/2Parcial/blob/main/examen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np


In [8]:
v=np.array([1,2,3])

In [10]:
w=np.array([2,2,2])

In [12]:
v+w

array([3, 4, 5])

In [13]:
2*v

array([2, 4, 6])

In [11]:
v+w
2*v
v*w

array([2, 4, 6])

In [23]:
x = np.array([0, 0.1*np.pi, 0.2*np.pi, 0.3*np.pi, 0.4*np.pi, 0.5*np.pi, 0.6*np.pi, 0.7*np.pi, 0.8*np.pi, 0.9*np.pi, np.pi])

In [39]:
x[3]

0.9424777960769379

In [40]:
x[5]

1.5707963267948966

In [24]:
y=np.sin(x)

In [25]:
y

array([0.00000000e+00, 3.09016994e-01, 5.87785252e-01, 8.09016994e-01,
       9.51056516e-01, 1.00000000e+00, 9.51056516e-01, 8.09016994e-01,
       5.87785252e-01, 3.09016994e-01, 1.22464680e-16])

In [26]:
np.linspace(0,np.pi,1000)

array([0.        , 0.00314474, 0.00628947, 0.00943421, 0.01257895,
       0.01572369, 0.01886842, 0.02201316, 0.0251579 , 0.02830264,
       0.03144737, 0.03459211, 0.03773685, 0.04088159, 0.04402632,
       0.04717106, 0.0503158 , 0.05346054, 0.05660527, 0.05975001,
       0.06289475, 0.06603949, 0.06918422, 0.07232896, 0.0754737 ,
       0.07861843, 0.08176317, 0.08490791, 0.08805265, 0.09119738,
       0.09434212, 0.09748686, 0.1006316 , 0.10377633, 0.10692107,
       0.11006581, 0.11321055, 0.11635528, 0.11950002, 0.12264476,
       0.1257895 , 0.12893423, 0.13207897, 0.13522371, 0.13836845,
       0.14151318, 0.14465792, 0.14780266, 0.15094739, 0.15409213,
       0.15723687, 0.16038161, 0.16352634, 0.16667108, 0.16981582,
       0.17296056, 0.17610529, 0.17925003, 0.18239477, 0.18553951,
       0.18868424, 0.19182898, 0.19497372, 0.19811846, 0.20126319,
       0.20440793, 0.20755267, 0.21069741, 0.21384214, 0.21698688,
       0.22013162, 0.22327635, 0.22642109, 0.22956583, 0.23271

In [32]:
numero=np.arange(5.)

In [33]:
numero[0]

0.0

In [34]:
numero[1:3]

array([1., 2.])

In [35]:
numero[:3]

array([0., 1., 2.])

In [36]:
numero[1:]

array([1., 2., 3., 4.])

In [37]:
numero[:]

array([0., 1., 2., 3., 4.])

In [38]:
numero[2:5:2]

array([2., 4.])

In [43]:
numero.mean()

2.0

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.linspace(0,30,5 )

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [41]:
x[-2]

2.827433388230814

In [ ]:
x[-1]

In [42]:
x[[0,1,-1]]

array([0.        , 0.31415927, 3.14159265])